blueprints/auth.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
from flask_wtf import FlaskForm
from werkzeug.security import check_password_hash, generate_password_hash
from wtforms.fields import (BooleanField, PasswordField, StringField,
                            SubmitField)
from wtforms.validators import (Email, EqualTo, Length, Regexp, Required,
                                ValidationError)
from model.user import get_user_by_email, insert_user

auth = Blueprint("auth", __name__)


class LoginForm(FlaskForm):
    email = StringField("Email address", [Required()])
    password = PasswordField("Password", [Required()])
    remember = BooleanField("Remember me")
    submit = SubmitField("Login")


@auth.route("/login")
def login():
    form = LoginForm()
    return render_template("login.html", form=form)


@auth.route("/login", methods=["POST"])
def login_post():
    form = LoginForm(request.form)

    if not form.validate():
        return render_template("login.html", form=form)

    user = get_user_by_email(form.email.data)

    if not user or not check_password_hash(user.password, form.password.data):
        flash("Please check your login details and try again.")
        return redirect(
            url_for("auth.login")
        )  # if the user doesn't exist or password is wrong, reload the page

    login_user(user, remember=form.remember.data)
    return redirect(url_for("main.index", user_id=current_user.id))


class RegistrationForm(FlaskForm):
    name = StringField("Name", [Required(), Length(min=4, max=40)])
    email = StringField("Email address", [Required(), Email()])
    password = PasswordField(
        "Password",
        [
            Required(),
            EqualTo("confirm", message="Passwords must match"),
            Length(min=8, message="Password be at least 8 characters"),
            Regexp("^(?=.*[a-z])", message="Password must have a lowercase character"),
            Regexp("^(?=.*[A-Z])", message="Password must have an uppercase character"),
            Regexp("^(?=.*\\d)", message="Password must contain a number"),
            Regexp(
                "(?=.*[@$!%*#?&])", message="Password must contain a special character"
            ),
        ],
    )
    confirm = PasswordField("Repeat password")
    submit = SubmitField("Signup")

    def validate_email(_form, field):
        if get_user_by_email(field.data):
            raise ValidationError("Email address already exists")


@auth.route("/signup")
def signup():
    form = RegistrationForm()
    return render_template("signup.html", form=form)


@auth.route("/signup", methods=["POST"])
def signup_post():
    form = RegistrationForm(request.form)

    if not form.validate():
        return render_template("signup.html", form=form)

    insert_user(
        form.email.data,
        form.name.data,
        generate_password_hash(form.password.data, method="sha256"),
    )

    flash("Thanks for registering! Please log in")
    return redirect(url_for("auth.login"))


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("main.index"))

templates/base.html
{%- extends "bootstrap/base.html" %}

{% block title %}Exercise Tracker{% endblock %}

{% block head %}
{{super()}}
{%- endblock %}

{% block styles -%}
    {{super()}}
    <link rel="stylesheet" type="text/css"
          href="{{url_for('static', filename='tracker-app.css')}}">
{% endblock %}

{% block navbar %}
{{nav.main_nav.render(renderer="my_bootstrap_renderer")}}
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}
<header class="jumbotron jumbotron-fluid vertical-center">
    <div class="container-fluid text-center"> 
       <h1 class="text-light">The Best Solution for Tracking Your Exercise</h1>
       <p class="text-light">We help you maximize your performance and become a healthier you</p>
       <p>
        <a href="{{ url_for('auth.signup') }}" class="btn btn-primary btn-lg" role="button">Sign up</a>
        <a href="{{ url_for('auth.login') }}" class="btn btn-secondary btn-lg" role="button">Login</a>
        </p>
    </div>
</header>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h3 class="text-center pt-5">Login</h3>
    <div class="container">
        <div id="login-row" class="row justify-content-center align-items-center">
            <div id="login-column" class="col-md-6">
                <div id="login-box" class="col-md-12">
                    {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        <div class="alert alert-danger" role="alert">
                            {{ messages[0] }}
                        </div>
                    {% endif %}
                    {% endwith %}
                    {{form|render_form()}}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/overview.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row mt-3 mb-3">
        <div class="col-md-12 d-flex">
            <h3 style="display:inline">Overview of your exercises ({{ period }})</h3><span style="margin: 0 50px;"><a href="/exercise" class="btn btn-primary ml-auto">Add exercise session</a></span>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
                <table class="table mb-4">
                    <tr>
                        <th scope="row">Total number of exercise sessions</th>
                        <td>{{ tot_exercises }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Total recorded duration of sessions</th>
                        <td>{{ tot_duration }}</td>
                    </tr>
                </table>   
                <h4>Exercises by type</h4>
                <table class="table mb-4">
                    <tr>
                        <th scope="col">Activity</th>
                        <th scope="col">Sessions</th>
                    </tr>
                    {% for activity in exercises_by_activity %}
                    <tr>
                        <td>{{ activity[0] }}</td>
                        <td>{{ activity[1] }}</td>
                    </tr>
                    {% endfor %}
                </table>
                <h4>Subactivities by type</h4>
                <table class="table">
                    <tr>
                        <th scope="col">Activity</th>
                        <th scope="col">Subactivity</th>
                        <th scope="col">Total</th>
                    </tr>
                    {% for activity in subactivities %}
                    <tr>
                        <td>{{ activity[0] }}</td>
                        <td>{{ activity[1] }}</td>
                        <td>{{ activity[2] }}</td>
                    </tr>
                    {% endfor %}
                </table>
                
        </div>
        <div class="col-md-6">
            <div class="mb-4">
                User <b>{{ user.email }} {% if user.name %} ({{ user.name }})</b> {% endif %}
            </div>
            View summary for:<p>
            <div><a href="?days=7">Last week</a></div>
            <div><a href="?days=30">Last month</a></div>
            <div><a href="?days=365">Last year</a></div>
            <div><a href="/">All time</a></div>

        </div>
    </div>
</div>
{% endblock %}

templates/signup.html
{% import "bootstrap/wtf.html" as wtf %}

{%- extends "base.html" %}

{% block content %}
<div class="container">
    <h3 class="text-center pt-5">Signup</h3>
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-md-6">
                {{form|render_form()}}
            </div>
        </div>
    </div>
</div>
{% endblock %}